name: Deploy to Azure Static Web Apps (Production)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "18.x"      # CRA is stable on Node 18
      APP_LOCATION: "."         # repo root (use "." not "/")
      API_LOCATION: ""          # no API/backend
      OUTPUT_LOCATION: "build"  # CRA outputs to build/
      CI: "false"               # don't fail on warnings

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Use npm 9 (avoids npm@10 idealTree issues) and isolate cache
      - name: Prepare npm (pin v9 + temp cache)
        run: |
          npm -v
          npm i -g npm@9
          npm -v
          npm config set fund false
          npm config set audit false
          npm config set cache "${{ runner.temp }}/npm-cache" --global
          npm cache verify
          rm -rf node_modules package-lock.json || true

      # Install project deps
      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --no-fund
        working-directory: ${{ env.APP_LOCATION }}

      # 🔧 Patch: ensure Ajv v8 + ajv-keywords v5 are present for CRA toolchain
      - name: Patch ajv toolchain
        run: npm install ajv@^8 ajv-keywords@^5 --no-save
        working-directory: ${{ env.APP_LOCATION }}

      # Build the app
      - name: Build
        run: npm run build
        working-directory: ${{ env.APP_LOCATION }}

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          production_branch: "master"
