name: Deploy to Azure Static Web Apps (Production)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      APP_LOCATION: "/"
      API_LOCATION: ""
      OUTPUT_LOCATION: "build"
      NODE_VERSION: "18.x"
      CI: "false"   # CRA: don’t fail on warnings in CI

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ${{ env.APP_LOCATION }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.APP_LOCATION }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          production_branch: "master"
