name: Deploy to Azure Static Web Apps (Production)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "18.x"      # CRA works best on Node 18
      APP_LOCATION: "/"         # repo root for SWA upload
      API_LOCATION: ""          # no API/backend
      OUTPUT_LOCATION: "build"  # CRA outputs to build/
      CI: "false"               # don't fail on warnings in CI

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Pin npm 9 and isolate cache to avoid npm@10 "idealTree" and cache ENOTEMPTY issues
      - name: Pin npm 9 and set temp cache
        run: |
          npm -v
          npm i -g npm@9
          npm -v
          npm config set fund false
          npm config set audit false
          npm config set cache "${{ runner.temp }}/npm-cache" --global
          npm cache verify
          rm -rf node_modules package-lock.json || true

      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          production_branch: "master"
