    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # ✅ Pin npm 9 and move cache to a temp dir (avoid ENOTEMPTY)
      - name: Pin npm 9 and set temp cache
        run: |
          npm -v
          npm i -g npm@9
          npm -v
          npm config set fund false
          npm config set audit false
          npm config set cache "${{ runner.temp }}/npm-cache" --global
          npm cache verify
          rm -rf node_modules package-lock.json || true
        working-directory: ${{ env.APP_LOCATION }}

      - name: Install dependencies (npm 9)
        run: npm install --legacy-peer-deps --no-audit --no-fund
        working-directory: ${{ env.APP_LOCATION }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.APP_LOCATION }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          production_branch: "master"
