name: Deploy to Azure Static Web Apps (Production)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_LOCATION: "/"
  API_LOCATION: ""
  OUTPUT_LOCATION: "build"  # CRA uses build/
  NODE_VERSION: "18.x"      # older CRA works best on Node 18

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies (clean)
        run: npm ci
        working-directory: ${{ env.APP_LOCATION }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.APP_LOCATION }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          production_branch: "main"
